---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.secrets.mgr
  resources:
  - secretmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.secrets.mgr
  resources:
  - secretmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - api.secrets.mgr
  resources:
  - secretmanagers/status
  verbs:
  - get
  - patch
  - update
