# permissions for end users to view secretmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretmanager-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secret-manager-opr
    app.kubernetes.io/part-of: secret-manager-opr
    app.kubernetes.io/managed-by: kustomize
  name: secretmanager-viewer-role
rules:
- apiGroups:
  - api.secrets.mgr
  resources:
  - secretmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.secrets.mgr
  resources:
  - secretmanagers/status
  verbs:
  - get
