apiVersion: api.secrets.mgr/v1alpha1
kind: SecretManager
metadata:
  labels:
    app.kubernetes.io/name: secretmanager
    app.kubernetes.io/instance: secretmanager-sample
    app.kubernetes.io/part-of: secret-manager-opr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: secret-manager-opr
  name: secretmanager-sample
spec:
  type: docker
  data:
    .dockerconfigjson: "eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby9hdXRoIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6ImFkbWluIn19fQ=="
  matchNamespace:
  - test*
  avoidNamespace:
  - test1
